version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: images/bench
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: images/nginx
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: images/worker
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: images/socketio
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: images/socketio
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
